# Generated by Django 4.0.6 on 2023-03-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualwebsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/images/')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('link_to_code', models.URLField(blank=True)),
                ('link_to_live_app', models.URLField(blank=True)),
            ],
        ),
    ]
